
languageCode: "en-us"
baseUrl: "https://luthercss.github.io/"
title: "ACM Luther College"
theme: "anubis"
paginate: 10
# disqusShortname: yourdiscussshortname
# googleAnalytics: UA-123-45
enableRobotsTXT: true

menu:
  main:
  - identifier: about
    name: About
    title: About
    url: https://luthercss.github.io
    weight: 2
  - identifier: posts
    name: Posts
    title: Posts
    url: /posts/
    weight: 0


params:
  author: "ACM Luther College"
  description: "Also known as the Computer Science Society, we are the ACM Student Chapter at Luther College."
  images:
    - static/images/featured.png # relative path to "static" directory
  customCSS:
    - css/my.css # relative path to "static" directory
  customJS:
    - js/main.js # relative path to "static" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: auto
  readMore: false

markup:
  goldmark:
    renderer:
      unsafe: false # enable raw HTML in Markdown